### ISSUE TITLE
concatenate representations from more layers

### ISSUE THREAD

**Issue by yassmine-lam** [akoksal/BERT-Sentiment-Analysis-Turkish#5]
Hi,

Thank u for answering to my previous issue. 
Can u plz explain how to concatentae the representations from the last four hidden layers instead of using olny the last layer?

Also did u tried to fine tune the extracted bert features? do u think it will improve the performance?
Thank u

**Comment by akoksal** [comment]
Sorry for my rather late reply.
You can change ```feature_extraction``` function in [this notebook](https://github.com/akoksal/BERT-Sentiment-Analysis-Turkish/blob/master/BERT%20Features%20with%20Keras.ipynb) to get other hidden features as well. But for finetuning BERT models instead of just finetuning extracted BERT features, you'd need to use PyTorch models. You can check notebooks in [this repo](https://github.com/boun-tabi/BounTi-Turkish-Sentiment-Analysis).
